'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4984
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Properties.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property

		Friend Shared ReadOnly Property big_arrow_down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("big_arrow_down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property big_arrow_up() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("big_arrow_up", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property dnt_demo_icon() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("dnt_demo_icon", resourceCulture)
				Return DirectCast(obj, System.Drawing.Icon)
			End Get
		End Property

		Friend Shared ReadOnly Property main_bg() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("main_bg", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxAddBarcode_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxAddBarcode_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxAddBarcode_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxAddBarcode_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxAddBarcode_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxAddBarcode_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxAddBarcode_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxAddBarcode_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxAnnotationBar() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxAnnotationBar", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxClose_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxClose_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxClose_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxClose_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxClose_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxClose_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCrop_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCrop_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCrop_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCrop_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCrop_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCrop_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCrop_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCrop_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCurrentImage_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCurrentImage_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCut_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCut_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCut_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCut_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCut_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCut_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxCut_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxCut_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDelete_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDelete_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDelete_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDelete_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDelete_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDelete_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDelete_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDelete_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAll_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAll_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAll_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAll_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAll_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAll_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAll_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAll_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAnnotationA_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAnnotationA_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAnnotationA_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAnnotationA_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAnnotationA_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAnnotationA_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxDeleteAnnotationA_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxDeleteAnnotationA_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipse_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipse_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipse_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipse_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipse_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipse_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipse_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipse_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipseA_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipseA_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipseA_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipseA_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipseA_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipseA_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxEllipseA_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxEllipseA_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFirst_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFirst_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFirst_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFirst_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFirst_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFirst_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFirst_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFirst_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFit_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFit_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFit_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFit_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFit_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFit_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFit_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFit_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFlip_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFlip_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFlip_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFlip_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFlip_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFlip_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxFlip_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxFlip_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxGrab_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxGrab_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxGrab_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxGrab_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxGrab_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxGrab_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxGrab_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxGrab_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxHand_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxHand_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxHand_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxHand_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxHand_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxHand_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

        Friend Shared ReadOnly Property picboxHand_Leave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picboxHand_Leave", resourceCulture)
                Return DirectCast(obj, System.Drawing.Bitmap)
            End Get
        End Property

		Friend Shared ReadOnly Property picboxLast_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLast_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLast_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLast_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLast_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLast_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLast_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLast_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLine_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLine_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLine_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLine_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLine_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLine_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLine_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLine_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLineA_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLineA_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLineA_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLineA_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLineA_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLineA_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLineA_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLineA_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLoadImage_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLoadImage_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLoadImage_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLoadImage_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLoadImage_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLoadImage_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxLoadImage_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxLoadImage_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMax_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMax_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMax_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMax_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMax_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMax_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMin_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMin_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMin_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMin_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMin_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMin_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMirror_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMirror_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMirror_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMirror_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMirror_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMirror_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxMirror_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxMirror_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxNext_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxNext_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxNext_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxNext_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxNext_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxNext_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxNext_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxNext_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOCR_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOCR_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOCR_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOCR_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOCR_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOCR_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOCR_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOCR_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOriginalSize_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOriginalSize_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOriginalSize_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOriginalSize_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOriginalSize_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOriginalSize_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxOriginalSize_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxOriginalSize_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPoint_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPoint_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPoint_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPoint_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPoint_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPoint_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPoint_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPoint_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPrevious_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPrevious_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPrevious_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxPrevious_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxPrevious_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxReadBarcode_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxReadBarcode_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxReadBarcode_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxReadBarcode_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxReadBarcode_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxReadBarcode_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxReadBarcode_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxReadBarcode_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangle_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangle_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangle_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangle_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangle_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangle_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangle_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangle_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangleA_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangleA_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangleA_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangleA_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangleA_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangleA_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRectangleA_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRectangleA_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxResample_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxResample_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxResample_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxResample_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxResample_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxResample_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxResample_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxResample_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateLeft_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateLeft_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateLeft_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateLeft_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateLeft_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateLeft_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateLeft_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateLeft_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateRight_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateRight_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateRight_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateRight_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateRight_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateRight_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxRotateRight_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxRotateRight_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxSave_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxSave_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxSave_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxSave_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxSave_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxSave_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxSave_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxSave_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxScan_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxScan_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxScan_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxScan_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxScan_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxScan_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxScan_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxScan_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxText_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxText_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxText_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxText_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxText_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxText_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxText_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxText_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxTextA_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxTextA_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxTextA_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxTextA_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxTextA_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxTextA_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxTextA_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxTextA_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxTotalImage_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxTotalImage_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoom_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoom_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoom_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoom_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoom_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoom_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoom_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoom_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomIn_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomIn_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomIn_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomIn_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomIn_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomIn_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomIn_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomIn_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomOut_Disabled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomOut_Disabled", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomOut_Down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomOut_Down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomOut_Enter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomOut_Enter", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property picboxZoomOut_Leave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("picboxZoomOut_Leave", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property small_arrow_down() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("small_arrow_down", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property

		Friend Shared ReadOnly Property small_arrow_up() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("small_arrow_up", resourceCulture)
				Return DirectCast(obj, System.Drawing.Bitmap)
			End Get
		End Property
	End Class
End Namespace
